# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyValue.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyValue.proto',
  package='eu.stratosphere.language.binding.protos',
  serialized_pb='\n\x0ekeyValue.proto\x12\'eu.stratosphere.language.binding.protos\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"W\n\x0eKeyValueStream\x12\x45\n\x06record\x18\x01 \x03(\x0b\x32\x35.eu.stratosphere.language.binding.protos.KeyValuePairB\x10\x42\x0eKeyValueProtos')




_KEYVALUEPAIR = _descriptor.Descriptor(
  name='KeyValuePair',
  full_name='eu.stratosphere.language.binding.protos.KeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eu.stratosphere.language.binding.protos.KeyValuePair.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='eu.stratosphere.language.binding.protos.KeyValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=101,
)


_KEYVALUESTREAM = _descriptor.Descriptor(
  name='KeyValueStream',
  full_name='eu.stratosphere.language.binding.protos.KeyValueStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='eu.stratosphere.language.binding.protos.KeyValueStream.record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=190,
)

_KEYVALUESTREAM.fields_by_name['record'].message_type = _KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['KeyValuePair'] = _KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['KeyValueStream'] = _KEYVALUESTREAM

class KeyValuePair(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYVALUEPAIR

  # @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.KeyValuePair)

class KeyValueStream(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYVALUESTREAM

  # @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.KeyValueStream)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\016KeyValueProtos')
# @@protoc_insertion_point(module_scope)
