// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyValue.proto

package eu.stratosphere.language.binding.protos;

public final class KeyValueProtos {
  private KeyValueProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValuePairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code eu.stratosphere.language.binding.protos.KeyValuePair}
   */
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessage
      implements KeyValuePairOrBuilder {
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValuePair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValuePair defaultInstance;
    public static KeyValuePair getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValuePair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValuePair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.class, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValuePair> PARSER =
        new com.google.protobuf.AbstractParser<KeyValuePair>() {
      public KeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValuePair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValuePair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.stratosphere.language.binding.protos.KeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.class, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder.class);
      }

      // Construct using eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor;
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair getDefaultInstanceForType() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.getDefaultInstance();
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair build() {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair buildPartial() {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair result = new eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair) {
          return mergeFrom((eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair other) {
        if (other == eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eu.stratosphere.language.binding.protos.KeyValuePair)
    }

    static {
      defaultInstance = new KeyValuePair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.KeyValuePair)
  }

  public interface KeyValueStreamOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> 
        getRecordList();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair getRecord(int index);
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    int getRecordCount();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    java.util.List<? extends eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder> 
        getRecordOrBuilderList();
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder getRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code eu.stratosphere.language.binding.protos.KeyValueStream}
   */
  public static final class KeyValueStream extends
      com.google.protobuf.GeneratedMessage
      implements KeyValueStreamOrBuilder {
    // Use KeyValueStream.newBuilder() to construct.
    private KeyValueStream(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueStream(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueStream defaultInstance;
    public static KeyValueStream getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueStream getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueStream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                record_ = new java.util.ArrayList<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair>();
                mutable_bitField0_ |= 0x00000001;
              }
              record_.add(input.readMessage(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = java.util.Collections.unmodifiableList(record_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.class, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueStream> PARSER =
        new com.google.protobuf.AbstractParser<KeyValueStream>() {
      public KeyValueStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueStream(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueStream> getParserForType() {
      return PARSER;
    }

    // repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;
    public static final int RECORD_FIELD_NUMBER = 1;
    private java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> record_;
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    public java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    public java.util.List<? extends eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder> 
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    public int getRecordCount() {
      return record_.size();
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair getRecord(int index) {
      return record_.get(index);
    }
    /**
     * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
     */
    public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }

    private void initFields() {
      record_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getRecordCount(); i++) {
        if (!getRecord(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < record_.size(); i++) {
        output.writeMessage(1, record_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < record_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, record_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.stratosphere.language.binding.protos.KeyValueStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.class, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.Builder.class);
      }

      // Construct using eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRecordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor;
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream getDefaultInstanceForType() {
        return eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.getDefaultInstance();
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream build() {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream buildPartial() {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream result = new eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream(this);
        int from_bitField0_ = bitField0_;
        if (recordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            record_ = java.util.Collections.unmodifiableList(record_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.record_ = record_;
        } else {
          result.record_ = recordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream) {
          return mergeFrom((eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream other) {
        if (other == eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream.getDefaultInstance()) return this;
        if (recordBuilder_ == null) {
          if (!other.record_.isEmpty()) {
            if (record_.isEmpty()) {
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordIsMutable();
              record_.addAll(other.record_);
            }
            onChanged();
          }
        } else {
          if (!other.record_.isEmpty()) {
            if (recordBuilder_.isEmpty()) {
              recordBuilder_.dispose();
              recordBuilder_ = null;
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRecordFieldBuilder() : null;
            } else {
              recordBuilder_.addAllMessages(other.record_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRecordCount(); i++) {
          if (!getRecord(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValueStream) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;
      private java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> record_ =
        java.util.Collections.emptyList();
      private void ensureRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = new java.util.ArrayList<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair>(record_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder> recordBuilder_;

      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> getRecordList() {
        if (recordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(record_);
        } else {
          return recordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public int getRecordCount() {
        if (recordBuilder_ == null) {
          return record_.size();
        } else {
          return recordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair getRecord(int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);
        } else {
          return recordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder setRecord(
          int index, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.set(index, value);
          onChanged();
        } else {
          recordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder setRecord(
          int index, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder addRecord(eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(value);
          onChanged();
        } else {
          recordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder addRecord(
          int index, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(index, value);
          onChanged();
        } else {
          recordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder addRecord(
          eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder addRecord(
          int index, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder addAllRecord(
          java.lang.Iterable<? extends eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair> values) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          super.addAll(values, record_);
          onChanged();
        } else {
          recordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder clearRecord() {
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public Builder removeRecord(int index) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.remove(index);
          onChanged();
        } else {
          recordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder getRecordBuilder(
          int index) {
        return getRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder getRecordOrBuilder(
          int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);  } else {
          return recordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public java.util.List<? extends eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder> 
           getRecordOrBuilderList() {
        if (recordBuilder_ != null) {
          return recordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(record_);
        }
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder addRecordBuilder() {
        return getRecordFieldBuilder().addBuilder(
            eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder addRecordBuilder(
          int index) {
        return getRecordFieldBuilder().addBuilder(
            index, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.stratosphere.language.binding.protos.KeyValuePair record = 1;</code>
       */
      public java.util.List<eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder> 
           getRecordBuilderList() {
        return getRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder> 
          getRecordFieldBuilder() {
        if (recordBuilder_ == null) {
          recordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePair.Builder, eu.stratosphere.language.binding.protos.KeyValueProtos.KeyValuePairOrBuilder>(
                  record_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          record_ = null;
        }
        return recordBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.stratosphere.language.binding.protos.KeyValueStream)
    }

    static {
      defaultInstance = new KeyValueStream(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.stratosphere.language.binding.protos.KeyValueStream)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016keyValue.proto\022\'eu.stratosphere.langua" +
      "ge.binding.protos\"*\n\014KeyValuePair\022\013\n\003key" +
      "\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"W\n\016KeyValueStream\022" +
      "E\n\006record\030\001 \003(\01325.eu.stratosphere.langua" +
      "ge.binding.protos.KeyValuePairB\020B\016KeyVal" +
      "ueProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_stratosphere_language_binding_protos_KeyValuePair_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_stratosphere_language_binding_protos_KeyValueStream_descriptor,
              new java.lang.String[] { "Record", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
